# Generated by Django 5.0.2 on 2024-05-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_news_date_news_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='char_count_received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='char_count_requested',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='model_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
